server:
  port: 8082
spring:
  application:
    name: hcl-payment-service
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
    datasource:
      url: jdbc:h2:mem:payments
      driverClassName: org.h2.Driver
      username: payment
      password: payment
      platform: org.hibernate.dialect.H2Dialect
    jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect